language: python
python:
  - "2.7"

env:
  - "DJANGO_VERSION=1.6"
  - "DJANGO_VERSION=1.7"

install:
  - cd testapp
  - python install_deps.py

script:
  - python manage.py test

after_script:
  - cd ..
  - rm django_tests